### ISSUE TITLE
thoughts about refactoring

### ISSUE THREAD

**Issue by Wirnex** [OAGr/foretold#23]
- create base class CrudData with interface getAll, getOne, createOne, updateOne, deleteOne
- pull out authentication and permissions to CrudData
- use single updateOne instead of archive, unarchive, edit, etc. ?
- use graphql pagination

**Comment by OAGr** [comment]
I like that proposal, seems worth an attempt with one model, then we could extend it to the entire app. 

I'm a bit hesitant about ``updateOne``, because I think it's a bit of an anti-pattern, but think it would probably speed up short-term development, so it's probably a good idea.

**Comment by OAGr** [comment]
I imagine that ``getAll`` could be tricky. It's somewhat of a search, which may be difficult to make generic. Perhaps there could be a simple version, and it could be overridden, or a custom ``search`` query could be added for specific models.

Also, note that we probably will need to further specify how graphql pagination and inputs would work. I think that having single combined inputs (instead of several variables) is preferrable. For pagination, I think that ``offset`` and ``limit`` is probably fine, but would be open to other ideas.

We'll also eventually have to figure out how to do some fuzzy text search system, but not yet.

**Comment by OAGr** [comment]
@Wirnex  Can I close this at this time?
